### ISSUE TITLE
bug: User Delete 관련 사항

### ISSUE THREAD

**Issue by happyjamy** [SeoulGreenJacket/Dr.Trash#13]
user DB 에서 user를 삭제하려고 하면 error 가 떠요

![스크린샷 2022-08-31 오전 1 25 46](https://user-images.githubusercontent.com/78072370/187607947-661e274e-0546-4c19-a4a0-fd765789f772.png)

외래키로 묶여있는 것들때문에 참조 무결성 문제가 발생하는 것 같은데
db 스키마 상에서 이걸 어떻게 할지 결정해야 하는 문제 인 것 같습니다~

❓ 관련 정보들도 유저 삭제 시 삭제하는 걸로 할까요?

**Comment by seheon99** [comment]
- `achiever`: 삭제
- `trash`: 삭제
- `trashcan`: 삭제
- `trashcanUsage`: 삭제
- `article`: 유지
- `comment`: 유지

이렇게 어때요

**Comment by happyjamy** [comment]
굳굳 좋습니다~~

**Comment by seheon99** [comment]
디비 레포에서 작업할게요~
