### ISSUE TITLE
enhance: 토큰 테이블

### ISSUE THREAD

**Issue by happyjamy** [SeoulGreenJacket/Dr.Trash#7]
## 개발사항

refresh 토큰 유효성 검사를 위해 db에 저장한 token 들을 만료기한이 지나면 자동으로 삭제하게 하는 크론잡을 만들어요

---

## 추가사항

화이팅!

**Comment by seheon99** [comment]
### 개발 사항
- [ ] `oauth` 테이블 삭제하고 유저 테이블에 `kakaoId` 컬럼 추가하기
- [ ] 로그아웃을 화이트리스트로 관리하기 위한 토큰 테이블 만들기
- [ ] 토큰 테이블에 존재하지만 만료된 토큰 데이터를 삭제하기 위한 `cron` 설정하기

### 추가사항
- Dr.Trash-BE 레포에서 이슈를 옮겨왔어요
